name: OctaneIntegration
on:
  workflow_run:
    workflows: [gradle-helloworld]
    types: [requested, in_progress, completed]
  pull_request:
    types: [opened, edited, closed, reopened]
  workflow_dispatch:  # Allows manual run from the Actions tab
env: 
    NODE_TLS_REJECT_UNAUTHORIZED: 0
jobs:   
  octane_integration_job:
    runs-on: [self-hosted]
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v1.0
        id: gitHubActionsIntegration
        with:
            octaneUrl: 'https://almoctane-ams.saas.microfocus.com'
            octaneSharedSpace: 322006
            octaneWorkspace: 34001
            octaneClientId: ${{secrets.OCTANE_CLIENT_ID}}
            octaneClientSecret: ${{secrets.OCTANE_CLIENT_SECRET}}
            githubToken: ${{secrets.GITHUB_TOKEN}}
            serverBaseUrl: 'https://github.com/thanhdphan/gradle-helloworld'
            unitTestResultsGlobPattern: "**/*.xml"
            logLevel: '2-debug'

            
