name: OctaneIntegration
on:
  workflow_run:
    workflows: [gradle-helloworld]
    types: [requested, in_progress, completed]
  pull_request:
    types: [opened, edited, closed, reopened]
env: 
    NODE_TLS_REJECT_UNAUTHORIZED: 0
jobs:   
  octane_integration_job:
    runs-on: octane
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v1.0
        id: gitHubActionsIntegration
        with:
            octaneUrl: 'https://almoctane-ams.saas.microfocus.com'
            octaneSharedSpace: 322006
            octaneWorkspace: 34001
            octaneClientId: ${{secrets.OCTANE_CLIENT_ID}}
            octaneClientSecret: ${{secrets.OCTANE_CLIENT_SECRET}}
            githubToken: ${{secrets.GITHUB_TOKEN}}
            serverBaseUrl: 'https://github.com/thanhdphan/gradle-helloworld'
            pipelineNamePattern: '${workflow_name}'
            unitTestResultsGlobPattern: '**/*.xml'
